#############################################################################
# Makefile for building: TAA
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  taa.pro
# Template: app
# Command: /home/cglover/Qt/5.11.1/gcc_64/bin/qmake -o Makefile taa.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DGLM_ENABLE_EXPERIMENTAL -DQT5BUILD -DFMT_HEADER_ONLY -DUSEGLM -DNGL_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -Wno-unused-variable -march=native -I/usr/include/SDL2 -D_REENTRANT -g -std=gnu++1z -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/cglover/NGL/include -I../common/include -I/public/devel/include -I/home/cglover/NGL/include -I/home/cglover/NGL/gl3w -Iinclude -I/home/cglover/Qt/5.11.1/gcc_64/include -I/home/cglover/Qt/5.11.1/gcc_64/include/QtOpenGL -I/home/cglover/Qt/5.11.1/gcc_64/include/QtWidgets -I/home/cglover/Qt/5.11.1/gcc_64/include/QtGui -I/home/cglover/Qt/5.11.1/gcc_64/include/QtCore -Imoc -isystem /usr/include/libdrm -I/home/cglover/Qt/5.11.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/cglover/Qt/5.11.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/cglover/Qt/5.11.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/cglover/Qt/5.11.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TAA1.0.0
DISTDIR = /home/cglover/uni/TAA/obj/TAA1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/cglover/NGL/lib -Wl,-z,origin -Wl,-rpath,\$$ORIGIN/L/home/cglover/NGL/lib -Wl,-rpath,/home/cglover/NGL/lib -Wl,-rpath,/home/cglover/Qt/5.11.1/gcc_64/lib
LIBS          = $(SUBLIBS) -lXi -ldl -lX11 -lXrandr -lXinerama -lXcursor -lXxf86vm -lGLEW -lGLU -lglfw3 -L/usr/local/lib -L/home/cglover/NGL/lib -l NGL -lSDL2 -L/home/cglover/Qt/5.11.1/gcc_64/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/usercamera.cpp \
		src/renderscene.cpp \
		src/objhandler.cpp \
		src/shaderhandler.cpp 
OBJECTS       = obj/main.o \
		obj/usercamera.o \
		obj/renderscene.o \
		obj/objhandler.o \
		obj/shaderhandler.o
DIST          = $OTHER_FILES \
		shaders/env_f.glsl \
		shaders/env_v.glsl \
		shaders/phong_f.glsl \
		shaders/phong_v.glsl \
		shaders/blit_v.glsl \
		shaders/blit_f.glsl \
		shaders/beckmann_v.glsl \
		shaders/beckmann_f.glsl \
		shaders/taa_f.glsl \
		shaders/taa_v.glsl \
		.qmake.stash \
		includes.pri \
		taa.pro include/renderscene.h \
		include/usercamera.h \
		include/objhandler.h \
		include/shaderhandler.h src/main.cpp \
		src/usercamera.cpp \
		src/renderscene.cpp \
		src/objhandler.cpp \
		src/shaderhandler.cpp
QMAKE_TARGET  = TAA
DESTDIR       = 
TARGET        = TAA


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: taa.pro .qmake.cache /home/cglover/Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf /home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/unix.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/linux.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/sanitize.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/g++-base.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/qconfig.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qt_config.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/toolchain.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/default_pre.prf \
		/home/cglover/NGL/UseNGL.pri \
		includes.pri \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/default_post.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/warn_on.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qt.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/resources.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/moc.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/uic.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qmake_use.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/file_copies.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/exceptions.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/yacc.prf \
		/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/lex.prf \
		taa.pro \
		/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5OpenGL.prl \
		/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5Widgets.prl \
		/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5Gui.prl \
		/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile taa.pro
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/spec_pre.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/unix.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/linux.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/sanitize.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/gcc-base.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/g++-base.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/common/g++-unix.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/qconfig.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qt_functions.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qt_config.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/toolchain.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/default_pre.prf:
/home/cglover/NGL/UseNGL.pri:
includes.pri:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/resolve_config.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/default_post.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/warn_on.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qt.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/resources.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/moc.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/unix/opengl.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/uic.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/unix/thread.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/qmake_use.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/file_copies.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/testcase_targets.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/exceptions.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/yacc.prf:
/home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/lex.prf:
taa.pro:
/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5OpenGL.prl:
/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5Widgets.prl:
/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5Gui.prl:
/home/cglover/Qt/5.11.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile taa.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/renderscene.h include/usercamera.h include/objhandler.h include/shaderhandler.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/usercamera.cpp src/renderscene.cpp src/objhandler.cpp src/shaderhandler.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -msse -msse2 -msse3 -march=native -Wno-unused-variable -march=native -I/usr/include/SDL2 -D_REENTRANT -g -std=gnu++1z -Wall -W -Wno-unused-parameter -dM -E -o moc/moc_predefs.h /home/cglover/Qt/5.11.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/main.o: src/main.cpp include/renderscene.h \
		/home/cglover/NGL/include/ngl/Obj.h \
		/home/cglover/NGL/include/ngl/AbstractMesh.h \
		/home/cglover/NGL/include/ngl/Types.h \
		/home/cglover/NGL/gl3w/gl3w.h \
		/home/cglover/NGL/gl3w/glcorearb.h \
		/home/cglover/NGL/include/ngl/fmt/format.h \
		/home/cglover/NGL/include/ngl/fmt/format.cc \
		/home/cglover/NGL/include/ngl/NGLMessage.h \
		/home/cglover/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/home/cglover/NGL/include/ngl/BBox.h \
		/home/cglover/NGL/include/ngl/Vec3.h \
		/home/cglover/NGL/include/ngl/Vec4.h \
		/home/cglover/NGL/include/ngl/Vec2.h \
		/home/cglover/NGL/include/ngl/AbstractVAO.h \
		/home/cglover/NGL/include/ngl/RibExport.h \
		/home/cglover/NGL/include/ngl/Texture.h \
		/home/cglover/NGL/include/ngl/Image.h \
		/home/cglover/NGL/include/ngl/NGLassert.h \
		/home/cglover/NGL/include/ngl/Text.h \
		/home/cglover/NGL/include/ngl/VAOFactory.h \
		/home/cglover/NGL/include/ngl/SimpleVAO.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/QFont \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qfont.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qtguiglobal.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qglobal.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qconfig.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qtcore-config.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsysinfo.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qlogging.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qflags.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qmutex.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qnumeric.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qversiontagging.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qtgui-config.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qnamespace.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstring.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qchar.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qbytearray.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qrefcount.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qarraydata.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringliteral.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringview.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qshareddata.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qhash.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qiterator.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qlist.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qalgorithms.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qpair.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringlist.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qregexp.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobject.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qcoreevent.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qmetatype.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobject_impl.h \
		/home/cglover/NGL/include/ngl/Mat4.h \
		include/objhandler.h \
		include/shaderhandler.h \
		include/usercamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/usercamera.o: src/usercamera.cpp include/usercamera.h \
		/home/cglover/NGL/include/ngl/Obj.h \
		/home/cglover/NGL/include/ngl/AbstractMesh.h \
		/home/cglover/NGL/include/ngl/Types.h \
		/home/cglover/NGL/gl3w/gl3w.h \
		/home/cglover/NGL/gl3w/glcorearb.h \
		/home/cglover/NGL/include/ngl/fmt/format.h \
		/home/cglover/NGL/include/ngl/fmt/format.cc \
		/home/cglover/NGL/include/ngl/NGLMessage.h \
		/home/cglover/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/home/cglover/NGL/include/ngl/BBox.h \
		/home/cglover/NGL/include/ngl/Vec3.h \
		/home/cglover/NGL/include/ngl/Vec4.h \
		/home/cglover/NGL/include/ngl/Vec2.h \
		/home/cglover/NGL/include/ngl/AbstractVAO.h \
		/home/cglover/NGL/include/ngl/RibExport.h \
		/home/cglover/NGL/include/ngl/Texture.h \
		/home/cglover/NGL/include/ngl/Image.h \
		/home/cglover/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/usercamera.o src/usercamera.cpp

obj/renderscene.o: src/renderscene.cpp include/renderscene.h \
		/home/cglover/NGL/include/ngl/Obj.h \
		/home/cglover/NGL/include/ngl/AbstractMesh.h \
		/home/cglover/NGL/include/ngl/Types.h \
		/home/cglover/NGL/gl3w/gl3w.h \
		/home/cglover/NGL/gl3w/glcorearb.h \
		/home/cglover/NGL/include/ngl/fmt/format.h \
		/home/cglover/NGL/include/ngl/fmt/format.cc \
		/home/cglover/NGL/include/ngl/NGLMessage.h \
		/home/cglover/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/home/cglover/NGL/include/ngl/BBox.h \
		/home/cglover/NGL/include/ngl/Vec3.h \
		/home/cglover/NGL/include/ngl/Vec4.h \
		/home/cglover/NGL/include/ngl/Vec2.h \
		/home/cglover/NGL/include/ngl/AbstractVAO.h \
		/home/cglover/NGL/include/ngl/RibExport.h \
		/home/cglover/NGL/include/ngl/Texture.h \
		/home/cglover/NGL/include/ngl/Image.h \
		/home/cglover/NGL/include/ngl/NGLassert.h \
		/home/cglover/NGL/include/ngl/Text.h \
		/home/cglover/NGL/include/ngl/VAOFactory.h \
		/home/cglover/NGL/include/ngl/SimpleVAO.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/QFont \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qfont.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qtguiglobal.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qglobal.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qconfig.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qtcore-config.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsysinfo.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qlogging.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qflags.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qmutex.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qnumeric.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qversiontagging.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qtgui-config.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qnamespace.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstring.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qchar.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qbytearray.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qrefcount.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qarraydata.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringliteral.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringview.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qshareddata.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qhash.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qiterator.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qlist.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qalgorithms.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qpair.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringlist.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qregexp.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobject.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qcoreevent.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qmetatype.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cglover/Qt/5.11.1/gcc_64/include/QtCore/qobject_impl.h \
		/home/cglover/NGL/include/ngl/Mat4.h \
		include/objhandler.h \
		include/shaderhandler.h \
		/home/cglover/NGL/include/ngl/NGLInit.h \
		/home/cglover/NGL/include/ngl/Singleton.h \
		/home/cglover/NGL/include/ngl/VAOPrimitives.h \
		/home/cglover/NGL/include/ngl/ShaderLib.h \
		/home/cglover/NGL/include/ngl/Shader.h \
		/home/cglover/NGL/include/ngl/ShaderProgram.h \
		/home/cglover/NGL/include/ngl/Util.h \
		/home/cglover/NGL/include/ngl/Mat2.h \
		/home/cglover/NGL/include/ngl/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/renderscene.o src/renderscene.cpp

obj/objhandler.o: src/objhandler.cpp include/objhandler.h \
		/home/cglover/NGL/include/ngl/Obj.h \
		/home/cglover/NGL/include/ngl/AbstractMesh.h \
		/home/cglover/NGL/include/ngl/Types.h \
		/home/cglover/NGL/gl3w/gl3w.h \
		/home/cglover/NGL/gl3w/glcorearb.h \
		/home/cglover/NGL/include/ngl/fmt/format.h \
		/home/cglover/NGL/include/ngl/fmt/format.cc \
		/home/cglover/NGL/include/ngl/NGLMessage.h \
		/home/cglover/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h \
		/home/cglover/NGL/include/ngl/BBox.h \
		/home/cglover/NGL/include/ngl/Vec3.h \
		/home/cglover/NGL/include/ngl/Vec4.h \
		/home/cglover/NGL/include/ngl/Vec2.h \
		/home/cglover/NGL/include/ngl/AbstractVAO.h \
		/home/cglover/NGL/include/ngl/RibExport.h \
		/home/cglover/NGL/include/ngl/Texture.h \
		/home/cglover/NGL/include/ngl/Image.h \
		/home/cglover/NGL/include/ngl/NGLassert.h \
		include/shaderhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/objhandler.o src/objhandler.cpp

obj/shaderhandler.o: src/shaderhandler.cpp include/shaderhandler.h \
		/home/cglover/NGL/include/ngl/Types.h \
		/home/cglover/NGL/gl3w/gl3w.h \
		/home/cglover/NGL/gl3w/glcorearb.h \
		/home/cglover/NGL/include/ngl/fmt/format.h \
		/home/cglover/NGL/include/ngl/fmt/format.cc \
		/home/cglover/NGL/include/ngl/NGLMessage.h \
		/home/cglover/NGL/include/ngl/MessageQueue/AbstractMessageConsumer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/shaderhandler.o src/shaderhandler.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

